### ISSUE TITLE
Cannot install node 0.12

### ISSUE THREAD

**Issue by franck34** [prantlf/node-posix-ext#4]
> posix-ext@0.1.1 install /var/www/nodectrl-ws/src/node_modules/posix-ext 
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: entrant dans le répertoire « /var/www/nodectrl-ws/src/node_modules/posix-ext/build »
    CXX(target) Release/obj.target/posix-ext/src/posix-ext.o
In file included from /root/.node-gyp/0.12.0/src/node.h:61:0,
                       from ../src/process-win.h:4,
                       from ../src/posix-ext.cc:1:
/root/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘void init(v8::Handlev8::Object)’:
/root/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/posix-ext.cc:11:15: error: within this context
make: **\* [Release/obj.target/posix-ext/src/posix-ext.o] Erreur 1
make: quittant le répertoire « /var/www/nodectrl-ws/src/node_modules/posix-ext/build »

**Comment by prantlf** [comment]
Yes, you're right. Thanks for reporting this! I've fixed the build for all Node.js versions >= 0.10 in the just released 0.1.2.

**Comment by prantlf** [comment]
Eventually fixed this in 0.2.5.
